[mgr]
sort_by = "natural"
sort_dir_first = true
show_hidden = false

[opener]
edit = [
    { run = "nvim %s", desc = "Neovim", for = "unix" },
]
play = [
    { run = "open %s", desc = "Open", for = "macos" },
    { run = "xdg-open %s1", desc = "Open", for = "linux" },
]
open = [
    { run = "open %s", desc = "Open", for = "macos" },
    { run = "xdg-open %s1", desc = "Open", for = "linux" },
]
reveal = [
    { run = "open -R %s1", desc = "Reveal", for = "macos" },
    { run = "xdg-open %d1", desc = "Reveal", for = "linux" },
]

[preview]
max_width = 600
max_height = 900

[tasks]
macro_workers = 10

[input]
cursor_blink = false
