# vim:fileencoding=utf-8

# Fonts
font_family MesloLGS NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Cursor
cursor_shape block
cursor_shape_unfocused hollow

# Performance
repaint_delay 10
input_delay 3

# Mouse
mouse_hide_wait 3.0

# Scrollback
scrollback_lines 10000

# Window
remember_window_size yes
window_border_width 0.5pt
draw_minimal_borders yes
hide_window_decorations titlebar-and-corners

# Colors (Gruvbox Dark)
foreground #dab9c2
background #1d2021
cursor #dab9c2

# Selection
selection_foreground #1d2021
selection_background #fe8019

# Window borders
active_border_color #fe8019
inactive_border_color #665c54
bell_border_color #fe8019

# Tab bar
tab_bar_edge bottom
tab_bar_style fade
tab_bar_min_tabs 1

# URLs
url_color #fe8019
url_style curly

# Audio bell
enable_audio_bell yes
